### ISSUE TITLE
错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main

### ISSUE THREAD

**Issue by bdrpc** [SweetInk/wqxuetang-pdf-downloader#19]
0210凌晨的最新版本

**Comment by weeshinwang** [comment]
我把`pom.xml`里的有一行
```
<mainClass>online.githuboy.wqxuetang.pdfd.Main</mainClass>
```
改成
```
<mainClass>online.githuboy.wqxuetang.pdfd.App</mainClass>
```
之后可以运行起来
但是最后还是报错，无法下载

**Comment by bdrpc** [comment]
> 我把`pom.xml`里的有一行
> 
> ```
> <mainClass>online.githuboy.wqxuetang.pdfd.Main</mainClass>
> ```
> 
> 改成
> 
> ```
> <mainClass>online.githuboy.wqxuetang.pdfd.App</mainClass>
> ```
> 
> 之后可以运行起来
> 但是最后还是报错，无法下载

嗯，改了可以运行，但是报“下载异常:Toolkit not initialized”

**Comment by meininghang** [comment]
+1。

**Comment by lovexuanqi521** [comment]
cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [charac
ter 2 line 1]
        at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:385)
        at cn.hutool.json.JSONObject.init(JSONObject.java:697)
        at cn.hutool.json.JSONObject.init(JSONObject.java:684)
        at cn.hutool.json.JSONObject.init(JSONObject.java:666)
        at cn.hutool.json.JSONObject.<init>(JSONObject.java:189)
        at cn.hutool.json.JSONObject.<init>(JSONObject.java:165)
        at cn.hutool.json.JSONObject.<init>(JSONObject.java:147)
        at cn.hutool.json.JSONObject.<init>(JSONObject.java:130)
        at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:67)
        at online.githuboy.wqxuetang.pdfd.FetchBookImageTask.lambda$requestNvc$0
(FetchBookImageTask.java:76)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.ja
va:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImp
l.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatch
er.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java
:186)
        at java.lang.Thread.run(Unknown Source)

下载一会会有这样的问题，然后延迟时间也在十来秒了

**Comment by SweetInk** [comment]
少提交了一个文件:cry:

**Comment by bdrpc** [comment]
> 少提交了一个文件😢

等你更新😁

**Comment by aniuyin** [comment]
[INFO ] 2020-02-10 13:39:38 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
[ERROR] 2020-02-10 13:39:39 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

**Comment by SweetInk** [comment]
> cn.hutool.json.JSONException: A JSONObject text must begin with '{' at 1 [charac
> ter 2 line 1]
> at cn.hutool.json.JSONTokener.syntaxError(JSONTokener.java:385)
> at cn.hutool.json.JSONObject.init(JSONObject.java:697)
> at cn.hutool.json.JSONObject.init(JSONObject.java:684)
> at cn.hutool.json.JSONObject.init(JSONObject.java:666)
> at cn.hutool.json.JSONObject.(JSONObject.java:189)
> at cn.hutool.json.JSONObject.(JSONObject.java:165)
> at cn.hutool.json.JSONObject.(JSONObject.java:147)
> at cn.hutool.json.JSONObject.(JSONObject.java:130)
> at cn.hutool.json.JSONUtil.parseObj(JSONUtil.java:67)
> at online.githuboy.wqxuetang.pdfd.FetchBookImageTask.lambda$requestNvc$0
> (FetchBookImageTask.java:76)
> at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.ja
> va:295)
> at java.security.AccessController.doPrivileged(Native Method)
> at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImp
> l.java:294)
> at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatch
> er.java:95)
> at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java
> :186)
> at java.lang.Thread.run(Unknown Source)
> 
> 下载一会会有这样的问题，然后延迟时间也在十来秒了

这个是NVC验证请求超时

**Comment by meininghang** [comment]
下载今天的最新版之后依旧报错：
> 错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main
原因: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by SweetInk** [comment]
> 下载今天的最新版之后依旧报错：
> 
> > 错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main
> > 原因: java.lang.NoClassDefFoundError: javafx/application/Application

Linux系统吗？

**Comment by meininghang** [comment]
> > 下载今天的最新版之后依旧报错：
> > > 错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main
> > > 原因: java.lang.NoClassDefFoundError: javafx/application/Application
> 
> Linux系统吗？

是 macOS Catalina 10.15.3。

**Comment by SweetInk** [comment]
> > > 下载今天的最新版之后依旧报错：
> > > > 错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main
> > > > 原因: java.lang.NoClassDefFoundError: javafx/application/Application
> > 
> > 
> > Linux系统吗？
> 
> 是 macOS Catalina 10.15.3。

搜索下你的`JRE`目录下是否有 `jfxrt.jar`

**Comment by meininghang** [comment]
> > > > 下载今天的最新版之后依旧报错：
> > > > > 错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main
> > > > > 原因: java.lang.NoClassDefFoundError: javafx/application/Application
> > > 
> > > 
> > > Linux系统吗？
> > 
> > 
> > 是 macOS Catalina 10.15.3。
> 
> 搜索下你的`JRE`目录下是否有 `jfxrt.jar`

请教一下怎么操作，完全不懂 Java 的具体操作。

**Comment by SweetInk** [comment]
> > > > > 下载今天的最新版之后依旧报错：
> > > > > > 错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main
> > > > > > 原因: java.lang.NoClassDefFoundError: javafx/application/Application
> > > > 
> > > > 
> > > > Linux系统吗？
> > > 
> > > 
> > > 是 macOS Catalina 10.15.3。
> > 
> > 
> > 搜索下你的`JRE`目录下是否有 `jfxrt.jar`
> 
> 请教一下怎么操作，完全不懂 Java 的具体操作。

参考这个链接：[Mac下查看已安装的jdk版本及其安装目录](https://www.cnblogs.com/smart-girl/p/10789099.html)

**Comment by meininghang** [comment]
> > > > > > 下载今天的最新版之后依旧报错：
> > > > > > > 错误: 找不到或无法加载主类 online.githuboy.wqxuetang.pdfd.Main
> > > > > > > 原因: java.lang.NoClassDefFoundError: javafx/application/Application
> > > > > 
> > > > > 
> > > > > Linux系统吗？
> > > > 
> > > > 
> > > > 是 macOS Catalina 10.15.3。
> > > 
> > > 
> > > 搜索下你的`JRE`目录下是否有 `jfxrt.jar`
> > 
> > 
> > 请教一下怎么操作，完全不懂 Java 的具体操作。
> 
> 参考这个链接：[Mac下查看已安装的jdk版本及其安装目录](https://www.cnblogs.com/smart-girl/p/10789099.html)

返回结果如下：
> Matching Java Virtual Machines (1):
    13.0.2, x86_64:	"Java SE 13.0.2"	/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home

**Comment by SweetInk** [comment]
在你的这个目录`/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home`下 搜索下有没有`jfxrt.jar`这个文件

**Comment by meininghang** [comment]
> 在你的这个目录`/Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home`下 搜索下有没有`jfxrt.jar`这个文件

没有。

**Comment by SweetInk** [comment]
去Oracle官网下载[jdk8](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)，把原来的卸载掉

**Comment by meininghang** [comment]
> 去Oracle官网下载[jdk8](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)，把原来的卸载掉

成功了！！！大神你太棒了！！！

**Comment by bdrpc** [comment]
下午重新下载最新版可以运行了。还有就是：
1、第一次运行，这本是270页左右的吧，到240页左右后面都报错了（240实际获取到206，没获取到的好像都是503错误？）
2、第二次运行，这本是300页左右吧，跑到第10页开始出现几KB文件。刷网页没有高清图，报“重新登陆”之类。重登也没有高清图，应该是封禁了，用新账号刷网页就有高清图了（封账号不封IP）。
推测默认的配置还是达到了阈值，建议再小一点，友好一点。。。

**Comment by bdrpc** [comment]
新账号重试下载，到第10页开始没有高清图，网页报“身份验证失败，请刷新或重新登录后重试”，新账号也被封禁。
配置已经改为10次就停顿60秒，默认休眠10秒，结果还是第10页开始被ban。推测是程序获取方式（相邻两个请求的间隔固定，连续多少次就封？改随机间隔时间试试？）或者指纹（没用burpsuit抓，盲猜UserAgent？UA列表，随机挑选试试？）等等被发现了，两次都是第10页开始被封
