### ISSUE TITLE
[ERROR] 2020-02-11 17:13:50 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 程序初始化失败

### ISSUE THREAD

**Issue by pkx0128** [SweetInk/wqxuetang-pdf-downloader#25]
[INFO ] 2020-02-11 17:13:49 [main] online.githuboy.wqxuetang.pdfd.utils.Cli - Parse commandline args:[-b, 3208724]
[INFO ] 2020-02-11 17:13:49 [main] online.githuboy.wqxuetang.pdfd.utils.Cli - 配置文件:/Volumes/ios/wqxuetang-pdf-downloader/target/config.properties 加载成功:
Config(threadCount=1, workPath=/Volumes/ios/wqxuetang-pdf-downloader/temp, cookie=acw_tc=3ccdc15b15813991266238665e2b8e60ff5d2c8bc15543689d80073b67451f; PHPSESSID=evrgoeei5vr40g2rq5qclbfpv7; _gid=400813368600; _gidv=a5534f99216b019069534e2f214f9b2a; Hm_lvt_a84b27ffd87daa3273555205ef60df89=1581399654,1581400078,1581400087,1581409471; ssxmod_itna=Yq0hYKYvMDkYi=DXDnCm5YRzAWDQqzbqDuQ1D0HIeGzDAxn40iDtoPTrlrK4ZrD0=E/a4wvNEbloO5iEQa43pWlUDAoDhx7QDox0=DnxAQDjar47RpxG4DEDm4DiDGeD+mqBYDRpPDCXDi8kx0CRcDToEIORx9FDB4oWo+elWGeb=0xxPb4KDWPqnDPplxexcD3oeee5QDe=Q3KatMxDDcxsCha4D===; ssxmod_itna2=Yq0hYKYvMDkYi=DXDnCm5YRzAWDQqzbqDuDxnK3e0=5DlobDjRxhylO4rRHC4mOsIcABd34LaSaEhqOekiRx0KnYoWD6Q7DLOOExEnhxXCFuHhXmLxkl8Ee+a8Zxp2App=L7zcwnhHlwUe+2tZz8ofGkK/CAU8Cl3ZYlpqK3LLYMplArUdV40KjliDZEwXm4fqATXKoPLrOkYgbDdYz29vtcUvG2FM/ljDsWcpWYvOmufmguda5pL8W9RvLrFMRUQXjLikpRgENGNkEkcviMpGjwNSzR2m/eLwT4/j5177RyRmt2Qjny6BqS7aQIx0fb=i4sep4ucQFWxE2DK4sAh=fxU4+v7bR379AKx2cO7hCivC9+B0pL9cd7oczOKCOXzaQ2HlIoFA0VAatsRYMytryDGihtwoBOk/v132btqPDSii3xdqS3WozKqfxa0PPTp7RxaQBFDKxKYDN4IUna8hirMrV0bR41BIC6qbQOAtAdqRC=yAR4bldedTGVboArhRbs2SFgkfnn5ixDKu5D7=DY95eD; Hm_lpvt_a84b27ffd87daa3273555205ef60df89=1581411912, maxRequestThreshold=45, waitingSeconds=60, defaultSleepTime=1500, bookId=3208724)
[INFO ] 2020-02-11 17:13:49 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
[INFO ] 2020-02-11 17:13:50 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - oldState:RUNNING -> newState:SUCCEEDED
netscape.javascript.JSException: ReferenceError: Can't find variable: getNVCVal
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:146)
	at com.sun.webkit.dom.JSObject.evalImpl(Native Method)
	at com.sun.webkit.dom.JSObject.eval(JSObject.java:63)
	at online.githuboy.wqxuetang.pdfd.ui.WebContainer.getNVC(WebContainer.java:55)
	at online.githuboy.wqxuetang.pdfd.ui.WebContainer.lambda$initEngine$2(WebContainer.java:72)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1287)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1398)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1280)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1267)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2499)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2343)
	at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
	at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:859)
	at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$103(URLLoader.java:850)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
[ERROR] 2020-02-11 17:13:50 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 程序初始化失败

**Comment by SweetInk** [comment]
`http://localhost:8081/nvc` 能不能访问

**Comment by jcyhcs** [comment]
不能访问，请问这个怎么访问

**Comment by BaldStrong** [comment]
> http://localhost:8081/nvc

我也出现上面这个问题了,我可以访问这个网址
![image](https://user-images.githubusercontent.com/37842039/75776932-ef9d6e80-5d8f-11ea-9778-e20957ac0977.png)
