### ISSUE TITLE
java.lang.NumberFormatException: For input string: "116 "

### ISSUE THREAD

**Issue by kiualen** [SweetInk/wqxuetang-pdf-downloader#26]
java.lang.NumberFormatException: For input string: "116 "
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at online.githuboy.wqxuetang.pdfd.App.lambda$handleSingleVolume$3(App.java:105)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at online.githuboy.wqxuetang.pdfd.App.handleSingleVolume(App.java:106)
        at online.githuboy.wqxuetang.pdfd.App.start(App.java:49)
        at online.githuboy.wqxuetang.pdfd.ui.WebContainer.lambda$null$1(WebContainer.java:80)
        at java.lang.Thread.run(Unknown Source)

**Comment by SweetInk** [comment]
看下你那个图片目录里有个`116 .jpg`的文件，文件名有空格
